fix: `AttributeError: module 'frappe' has no attribute 'get_single_value'` in older fw versions <16 (backport #1101) (#1102)
* fix: use `frappe.db.get_single_value` for compatibility with older fw versions (#1101)

(cherry picked from commit bc16b9284a95c306707e8b5c235072f726d9c721)

# Conflicts:
#	insights/api/__init__.py

* chore: resolve conflicts

---------

Co-authored-by: shahzeelahmed <35753732+shahzeelahmed@users.noreply.github.com>